export { Login } from "./Login/Login"
export { Register } from "./Register/Register"
export { Home } from "./Home/Home"
export { Search } from "./Search/Search"
export { Profile } from "./Profile/Profile"